//
// Created by Julian  on 22/11/15.
//

#ifndef SDLRTS_COMPONENTTYPE_H
#define SDLRTS_COMPONENTTYPE_H

enum ComponentType
{
    GRAPHICS_COMPONENT,
    TRANSFORM_COMPONENT,
    COLLISION_COMPONENT,
    CLICKABLE_COMPONENT
};

#endif //SDLRTS_COMPONENTTYPE_H
