//
// Created by Julian  on 22/11/15.
//

#ifndef COMPONENTTYPE_H
#define COMPONENTTYPE_H

enum ComponentType
{
    GRAPHICS_COMPONENT,
    TRANSFORM_COMPONENT,
    COLLISION_COMPONENT,
    CLICKABLE_COMPONENT
};

#endif //COMPONENTTYPE_H
